spring:
  devtools:
    restart:
      enabled: true
  datasource:
    url: ${POSTGRES_URI:jdbc:postgresql://localhost:5432/postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:admin}
    hikari:
      maximum-pool-size: ${CONNECTION_POOL_SIZE:10}
  sql:
    init:
      mode: always
  security:
    oauth2:
      resourceserver:

        jwt:
          jwk-set-uri: ${JWK_URI:http://localhost:8082/api/certificate/.well-known/jwks.json}