spring:
  application:
    name: education
  swagger:
    enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USER:nguyenvansang30102001@gmail.com}
    from: ${spring.mail.username}
    password: ${MAIL_PASSWORD:hybceitjopmgdela}
    protocol: ${MAIL_PROTOCOL:smtp}
    properties.mail.smtp:
      auth: true
      starttls.enable: true
    default-encoding: UTF-8

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: update
      generate_statistics: true
    properties:
      hibernate:
        jdbc:
          batch_size: 50
          order_inserts: true
          order_updates: true
          lob:
            non_contextual_creation: true

  profiles:
    active: ${ENV:dev}
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
      WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS: false
security:
  authentication:
    jwt:
      key-store: sang.jks
      key-store-password: 1234aA@
      key-alias: sang
      access-token-expires-in: 1d
      refresh-token-expires-in: 30d
      email-token-expires-in: 10m

server:
  port: ${PORT:8080}

#feign:
#  circuitbreaker:
#    enabled: true
#  okhttp:
#    enabled: true
#eureka:
#  instance:
#    prefer-ip-address: true
#    nonSecurePort: ${server.port}
#    secure-port-enabled: false
#  client:
#    serviceUrl:
#      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8081}/eureka/
app:
  iam:
    domain: http://localhost:4200
    client:
      authenticate-uri: /api/client/authenticate
      client-id: 46fa7bd2-eb87-41f7-82e5-576d9dee258b
      client-secret: mbMvn2YAnBfJH8JrkLVeXFJ72tbTEMUGUZDP8ZqKSYeMLi8XGqA0xcduji34hdv4Y3usA9S9B0IfYQJoX516M9sLQgTprSgalWZw


#  keytool -genkeypair -alias sang -keyalg RSA -keystore /home/nguyensang/DoAn/BE/iam/src/main/resources/sang.jks  -keypass 12346aA@ -storepass 1234aA@
template:
  folder: 'templates/excel'
  user:
    exportFileName: 'user_export_template.xlsx'
    importFileName: 'user_import_template.xlsx'
  question:
    importFileName: 'question_import_template.xlsx'

question-template:
  folder: 'templates/excel'
  question:
    importFileName: 'question_import_template.xlsx'