spring:
#  devtools:
#    restart:
#      enabled: true
  datasource:
    url: ${POSTGRES_URI:jdbc:postgresql://34.171.66.5:5432/postgres}
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASSWORD:admin}
    hikari:
      maximum-pool-size: ${CONNECTION_POOL_SIZE:10}
  sql:
    init:
      mode: always
  security:
    oauth2:
      resourceserver:

        jwt:
          jwk-set-uri: ${JWK_URI:http://localhost:9999/api/certificate/.well-known/jwks.json}